pipeline {
    agent any

    stages {
        stage ('Compile Stage') {

            steps {
                    sh 'echo mvn clean compile'
            }
        }

        stage ('Testing Stage') {

            steps {
                    sh 'echo mvn test'
            }
        }

        stage ('Deployment Stage') {
            steps {
                    sh 'echo mvn deploy'
            }
        }
    }
}
