pipeline {
  agent any
  parameters {
    string(name: 'stack',
      defaultValue: 'monkeystack',
      description: 'Please pick any stack to be installed.')
    choice(name: 'stack2',
      choices: 'zookeeper',
      description: 'Haha sorry, we just have these stacks.')
    choice(name: 'environment',
      choices: 'ntest\nlab\nmonkey',
      description: 'To which environment?')
    booleanParam(name: 'destructive_build',
      defaultValue: true,
      description: 'Do you want a destructive build?')
  }
  stages {
    stage('Checkout Fabric')
    {
      steps {
        git url: 'git@test.githost.io:infra-applications/infra-deploy.git'
        sh 'ls -al'
        sh 'ls -al scripts'
        sh 'ls -al scripts/deployments'
          sh 'chmod 755 scripts/deployment/deploy_quick.sh'
          sh './scripts/deployment/deploy_quick.sh'
      }
    }

    stage('Example') {
      steps {
        echo 'Hello World!'

        sh "echo fab update --parameter destructive=${params.destructive_build}"
        sh "echo ./bin/stack --parameter1=${params.stack} --parameter2=${params.stack2} --parameter3=${params.destructive_build}"
      }
    }
  }
}
